services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Kitodo\Dlf\:
    resource: '../Classes/*'

  Kitodo\Dlf\Command\DbDocsCommand:
    tags:
      - name: console.command
        command: 'kitodo:dbdocs'

  Kitodo\Dlf\Command\DeleteCommand:
    tags:
      - name: console.command
        command: 'kitodo:delete'

  Kitodo\Dlf\Command\HarvestCommand:
    tags:
      - name: console.command
        command: 'kitodo:harvest'

  Kitodo\Dlf\Command\IndexCommand:
    tags:
      - name: console.command
        command: 'kitodo:index'

  Kitodo\Dlf\Command\ReindexCommand:
    tags:
      - name: console.command
        command: 'kitodo:reindex'

  Kitodo\Dlf\Command\OptimizeCommand:
    tags:
      - name: console.command
        command: 'kitodo:optimize'

  Kitodo\Dlf\Command\SuggestBuildCommand:
    tags:
      - name: console.command
        command: 'kitodo:suggestBuild'

  Kitodo\Dlf\Common\TypoScriptHelper:
    public: true

  Kitodo\Dlf\Validation\DOMDocumentValidationStack:
    autowire: false

  Kitodo\Dlf\Validation\SaxonXslToSvrlValidator:
    autowire: false

  Kitodo\Dlf\Validation\XmlSchemesValidator:
    autowire: false
